### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by Leonardoeb** [UCSCLibrary/YouTubeImport#30]
I'm having trouble installing the plugin on omeka. Can someone help me?

**Fatal error: Uncaught Error: Class 'YoutubeImport_ImportHelper' not found in /var/www/omeka/plugins/YouTubeImport/YouTubeImportPlugin.php:101** 

Stack trace: #0 /var/www/omeka/application/libraries/Omeka/Plugin/Broker.php(142): YouTubeImportPlugin->hookInstall(Array) 
			 #1 /var/www/omeka/application/libraries/Omeka/Plugin/Installer.php(126): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin)) 
			 #2 /var/www/omeka/application/controllers/PluginsController.php(95): Omeka_Plugin_Installer->install(Object(Plugin)) 
			 #3 /var/www/omeka/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction() 
			 #4 /var/www/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction') 
			 #5 /var/www/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http)) 
			 #6 /var/www/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.ph in /var/www/omeka/plugins/YouTubeImport/YouTubeImportPlugin.php on line 101

**Comment by teo1978** [comment]
Same exact error on install.
Sad to see there hasn't even been a reply in 5 months.

Is this plugin being maintained?? If not, please remove it from the official plugins list.

**Comment by spswanz** [comment]
@Leonardoeb I got that error to go away by unticking the box in top nav Settings - Security for 'Enable HTML filtering' for the embed code to work.
