### ISSUE TITLE
error when installing YouTubeImport

### ISSUE THREAD

**Issue by michaeljaltman** [UCSCLibrary/YouTubeImport#32]
When I install the plugin I get this error:

Fatal error: Uncaught Error: Class 'YoutubeImport_ImportHelper' not found in /home/matthe18/public_html/omeka/plugins/YouTubeImport/YouTubeImportPlugin.php:101 Stack trace: #0 /home/matthe18/public_html/omeka/application/libraries/Omeka/Plugin/Broker.php(142): YouTubeImportPlugin->hookInstall(Array) #1 /home/matthe18/public_html/omeka/application/libraries/Omeka/Plugin/Installer.php(126): Omeka_Plugin_Broker->callHook('install', Array, Object(Plugin)) #2 /home/matthe18/public_html/omeka/application/controllers/PluginsController.php(95): Omeka_Plugin_Installer->install(Object(Plugin)) #3 /home/matthe18/public_html/omeka/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction() #4 /home/matthe18/public_html/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('installAction') #5 /home/matthe18/public_html/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request in /home/matthe18/public_html/omeka/plugins/YouTubeImport/YouTubeImportPlugin.php on line 101

**Comment by JenniferK1oo5** [comment]
I'm having this issue as well. I installed the plug in, it does not automatically show up on my control panel, I have to refresh it, then when I refresh the OMEKA site, it shows that error. And when I try to click on my items to view them, I get ""Omeka_Record_Exception
There is no element "Item Type Metadata", "Player"!"
Without the plugin, it works fine. I've tried uninstalling the plugin, removing it from the control panel, and re downloading and reinstalling it. But when I add it back, the issue comes back. I have no idea how to fix it, I'm not a tech person. and the OMEKA forums are inconclusive. But we need the plugin for our site. I have no idea how to navigate code and not entirely confident in trying to remove, edit or add lines. I tried just downloading the latest YouTubeImportPlugin.php file from here and replacing the old one, but it made me unable to view the plugin page on my site at all. When I tried downloading the plugin from GitHub in its entirely, it said invalid plugin. The download link on the omeka.org site does not have the updated version as shown on this site.  Would you be able to prove any assistance? Thanks!

**Comment by spswanz** [comment]
@JenniferK1oo5 I found a fix for me that works on 2.7. Basically the error is saying that it can't find the Player Item Metadata element, so manually create one and it will then work.  Details: Go to Item Types in the left sidebar and select edit for 'Moving Image'.  Select Add New Element at the bottom of the list and give it the element name "Player" and you can add "HTML embed code" to Description. 

@michaeljaltman I got that error to go away by unticking the box in top nav Settings - Security for 'Enable HTML filtering' for the embed code to work.

**Comment by dipualnur** [comment]
when performing Youtube plugin. ater clicking on "Install", this shows 
"Fatal error: Uncaught Error: Class "YoutubeImport_ImportHelper" not found in /var/www/html/omeka/plugins/YouTubeImport/YouTubeImportPlugin.php:101 Stack trace: #0 /var/www/html/omeka/application/libraries/Omeka/Plugin/Broker.php(142): YouTubeImportPlugin->hookInstall() #1 /var/www/html/omeka/application/libraries/Omeka/Plugin/Installer.php(126): Omeka_Plugin_Broker->callHook() #2 /var/www/html/omeka/application/controllers/PluginsController.php(100): Omeka_Plugin_Installer->install() #3 /var/www/html/omeka/application/libraries/Zend/Controller/Action.php(516): PluginsController->installAction() #4 /var/www/html/omeka/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch() #5 /var/www/html/omeka/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch() #6 /var/www/html/omeka/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(106): Zend_Controller_Front->dispatch() #7 /var/www/html/omeka/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run() #8 /var/www/html/omeka/application/libraries/Omeka/Application.php(73): Zend_Application->run() #9 /var/www/html/omeka/admin/index.php(28): Omeka_Application->run() #10 {main} thrown in /var/www/html/omeka/plugins/YouTubeImport/YouTubeImportPlugin.php on line 101"

after refreshing the page, it shows "the plugin is already have installed"
but after given a youtube link, it again shows error like this one 
"Fatal error: Array and string offset access syntax with curly braces is no longer supported in /var/www/html/omeka/plugins/YouTubeImport/libraries/Google/Utils.php on line 67"

Can anyone help me out ?
